@url = https://8080-coffee-mammal-kpw6dvir.ws-us21.gitpod.io

###
GET {{url}}/filmes

###
POST {{url}}/filmes
Content-Type: application/json

{
    "titulo": "Exemplo"
}

###
PUT {{url}}/filmes/4
Content-Type: application/json

{
    "titulo": "Ghostbusters"
}

###
DELETE {{url}}/filmes
Content-Type: application/json

{
    "id": 4
}
