GET https://8080-coffee-vulture-9g07xn7b.ws-us17.gitpod.io/8080-coffee-vulture-9g07xn7b.ws-us17.gitpod.io/filmes

###
POST https://8080-coffee-vulture-9g07xn7b.ws-us17.gitpod.io/8080-coffee-vulture-9g07xn7b.ws-us17.gitpod.io/filmes
Content-Type: application/json

{
    "titulo": "Exemplo"
}